//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strzelanka_w_Statki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wyniki
    {
        public int IDGracza { get; set; }
        public string Gracz { get; set; }
        public Nullable<int> Wynik { get; set; }
    }
}
