//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FakturaSprzedaży
    {
        public int NrFakturySprz { get; set; }
        public string Opis { get; set; }
        public System.DateTime DataWystawienia { get; set; }
        public int IDProduktu { get; set; }
        public decimal CenaNetto { get; set; }
        public decimal CenaBrutto { get; set; }
        public int IDKontrahenta { get; set; }
        public System.DateTime TerminPłatności { get; set; }
        public int VAT { get; set; }
    }
}
