//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrahenci
    {
        public int IDKontrahenta { get; set; }
        public string NazwaKontrahenta { get; set; }
        public string Adres { get; set; }
        public int NIP { get; set; }
        public string RodzajKonrahenta { get; set; }
        public string Stan { get; set; }
        public int NrFakturySprz { get; set; }
        public int NrFakturyZak { get; set; }
        public Nullable<decimal> Należność { get; set; }
        public Nullable<decimal> Zobowiązanie { get; set; }
    }
}
