//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty
    {
        public int IDProduktu { get; set; }
        public string NazwaProduktu { get; set; }
        public int IDKategori { get; set; }
        public int IlośćJedkostkowa { get; set; }
        public decimal CenaSprzedaży { get; set; }
        public decimal CenaZakupu { get; set; }
        public int StanMagazynu { get; set; }
    }
}
